version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/local/app/Dockerfile
    command: /start
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "443:8000"
    env_file:
      - .env
    depends_on:
      - postgres-db
    networks:
      - intropixel-network

  postgres-db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - intropixel-network

  # nginx:
  #   restart: always
  #   depends_on:
  #     - app
  #   volumes:
  #     - static_volume:/app/staticfiles
  #     - media_volume:/app/mediafiles
  #   build:
  #     context: ./docker/local/nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "443:80"
  #   networks:
  #     - intropixel-network

networks:
  intropixel-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
